# Generated by Django 3.1.1 on 2020-11-10 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookTitle', models.CharField(max_length=100)),
                ('bookAuthor', models.CharField(max_length=100)),
                ('bookCover', models.FileField(upload_to='media')),
                ('yearPublished', models.IntegerField()),
                ('bookTags', models.CharField(max_length=100)),
                ('bookSummary', models.CharField(max_length=100)),
                ('bookCategory', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arms.person')),
                ('userID', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('books', models.ManyToManyField(to='arms.Books')),
            ],
            options={
                'db_table': 'User',
            },
            bases=('arms.person',),
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arms.person')),
                ('userID', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('books', models.ManyToManyField(to='arms.Books')),
            ],
            options={
                'db_table': 'Administrator',
            },
            bases=('arms.person',),
        ),
    ]
