# Generated by Django 3.1.1 on 2020-11-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='books',
        ),
        migrations.RemoveField(
            model_name='user',
            name='person_ptr',
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
