# Generated by Django 3.1.1 on 2020-11-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_info',
        ),
    ]
