# Generated by Django 3.1.1 on 2020-11-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0002_remove_books_book_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_info',
            field=models.CharField(default='', max_length=100),
        ),
    ]
