# Generated by Django 3.1.1 on 2020-11-18 11:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arms', '0002_auto_20201118_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('admin_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Administrator',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('book_author_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('birthdate', models.DateField(default=datetime.datetime(2020, 11, 18, 19, 35, 43, 393756))),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
            ],
            options={
                'db_table': 'Author',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('book_category_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('book_category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('birthdate', models.DateField(default=datetime.datetime(2020, 11, 18, 19, 35, 43, 392757))),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arms.user')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arms.user')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=100)),
                ('book_cover', models.FileField(upload_to='media')),
                ('book_year', models.IntegerField()),
                ('book_tags', models.CharField(max_length=100)),
                ('book_summary', models.CharField(max_length=100)),
                ('book_info', models.CharField(max_length=100)),
                ('is_bookmarked', models.BooleanField()),
                ('is_downloaded', models.BooleanField()),
                ('is_read', models.BooleanField()),
                ('book_author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arms.author')),
                ('book_category_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arms.category')),
            ],
            options={
                'db_table': 'Books',
            },
        ),
    ]
