# Generated by Django 3.1.1 on 2020-11-18 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0003_administrator_author_books_category_employee_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2020, 11, 18, 19, 37, 18, 900973)),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2020, 11, 18, 19, 37, 18, 899927)),
        ),
    ]
