# Generated by Django 3.1.1 on 2020-11-29 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0003_books_book_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_info',
        ),
        migrations.AddField(
            model_name='books',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_year',
            field=models.DateField(),
        ),
    ]
