# Generated by Django 3.1.1 on 2020-11-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0004_auto_20201129_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
