# Generated by Django 3.1.1 on 2020-11-19 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0005_auto_20201118_2016'),
        ('arms', '0005_auto_20201118_2012'),
    ]

    operations = [
    ]
