# Generated by Django 3.1.1 on 2020-12-08 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0006_auto_20201130_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_author_id',
        ),
        migrations.RemoveField(
            model_name='books',
            name='book_category_no',
        ),
        migrations.AddField(
            model_name='books',
            name='birthdate',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='author_birthdate', to='arms.author'),
        ),
        migrations.AddField(
            model_name='books',
            name='book_author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='arms.author'),
        ),
        migrations.AddField(
            model_name='books',
            name='book_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='arms.category'),
        ),
        migrations.AddField(
            model_name='books',
            name='book_info',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='books',
            name='firstname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='author_firstname', to='arms.author'),
        ),
        migrations.AddField(
            model_name='books',
            name='lastname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='author_lastname', to='arms.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
