# Generated by Django 3.1.1 on 2020-11-21 11:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0007_auto_20201119_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_file',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2020, 11, 21, 11, 27, 1, 760848, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_cover',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2020, 11, 21, 11, 27, 1, 757850, tzinfo=utc)),
        ),
    ]
