# Generated by Django 3.1.1 on 2020-12-11 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0009_auto_20201209_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='books',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='books',
            name='lastname',
        ),
    ]
