# Generated by Django 3.1.1 on 2020-11-21 13:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0009_auto_20201121_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_info',
        ),
        migrations.AlterField(
            model_name='author',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2020, 11, 21, 13, 17, 5, 138784, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2020, 11, 21, 13, 17, 5, 136792, tzinfo=utc)),
        ),
    ]
