# Generated by Django 3.1.1 on 2020-12-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0010_auto_20201211_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bookmarkCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='downloadCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='readCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
