# Generated by Django 3.1.1 on 2020-12-14 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0011_auto_20201213_1809'),
        ('arms', '0011_auto_20201213_2219'),
    ]

    operations = [
    ]
