# Generated by Django 3.1.1 on 2020-12-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0012_merge_20201214_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='books',
            name='book_info',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_summary',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_title',
            field=models.CharField(max_length=500),
        ),
    ]
