# Generated by Django 3.1.1 on 2020-11-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0012_auto_20201122_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('S', 'Student'), ('E', 'Employee')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
