# Generated by Django 3.1.1 on 2020-11-27 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0014_remove_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
