# Generated by Django 2.2.17 on 2020-11-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0015_auto_20201128_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_info',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
