# Generated by Django 2.2.17 on 2020-11-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0016_books_book_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_info',
            field=models.CharField(default='', max_length=100),
        ),
    ]
